config/routes.rb
Rails.application.routes.draw do
  resources :spendings
  resources :departements
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/departement.rb
class Departement < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/spending.rb
class Spending < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departements_controller.rb
class DepartementsController < ApplicationController
  before_action :set_departement, only: %i[ show edit update destroy ]

  # GET /departements or /departements.json
  def index
    @departements = Departement.all
  end

  # GET /departements/1 or /departements/1.json
  def show
  end

  # GET /departements/new
  def new
    @departement = Departement.new
  end

  # GET /departements/1/edit
  def edit
  end

  # POST /departements or /departements.json
  def create
    @departement = Departement.new(departement_params)

    respond_to do |format|
      if @departement.save
        format.html { redirect_to departement_url(@departement), notice: "Departement was successfully created." }
        format.json { render :show, status: :created, location: @departement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departements/1 or /departements/1.json
  def update
    respond_to do |format|
      if @departement.update(departement_params)
        format.html { redirect_to departement_url(@departement), notice: "Departement was successfully updated." }
        format.json { render :show, status: :ok, location: @departement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departements/1 or /departements/1.json
  def destroy
    @departement.destroy

    respond_to do |format|
      format.html { redirect_to departements_url, notice: "Departement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departement
      @departement = Departement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departement_params
      params.require(:departement).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :departementID)
    end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  before_action :set_spending, only: %i[ show edit update destroy ]

  # GET /spendings or /spendings.json
  def index
    @spendings = Spending.all
  end

  # GET /spendings/1 or /spendings/1.json
  def show
  end

  # GET /spendings/new
  def new
    @spending = Spending.new
  end

  # GET /spendings/1/edit
  def edit
  end

  # POST /spendings or /spendings.json
  def create
    @spending = Spending.new(spending_params)

    respond_to do |format|
      if @spending.save
        format.html { redirect_to spending_url(@spending), notice: "Spending was successfully created." }
        format.json { render :show, status: :created, location: @spending }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spendings/1 or /spendings/1.json
  def update
    respond_to do |format|
      if @spending.update(spending_params)
        format.html { redirect_to spending_url(@spending), notice: "Spending was successfully updated." }
        format.json { render :show, status: :ok, location: @spending }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spendings/1 or /spendings/1.json
  def destroy
    @spending.destroy

    respond_to do |format|
      format.html { redirect_to spendings_url, notice: "Spending was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spending
      @spending = Spending.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spending_params
      params.require(:spending).permit(:employeeID, :date, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departements_helper.rb
module DepartementsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/views/departements/_departement.html.erb
<div id="<%= dom_id departement %>">
  <p>
    <strong>Name:</strong>
    <%= departement.name %>
  </p>

</div>

app/views/departements/_form.html.erb
<%= form_with(model: departement) do |form| %>
  <% if departement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departement.errors.count, "error") %> prohibited this departement from being saved:</h2>

      <ul>
        <% departement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departements/edit.html.erb
<div class="container">

<h1>Editing departement</h1>

<div>
  <%= link_to "Back to departements", departements_path %> | <%= link_to "Show this departement", @departement %> 
</div>
<%= render "form", departement: @departement %>

<br>


</div>

app/views/departements/index.html.erb
<div class="container">
  <h2>Departements</h2>
  <p><%= link_to "New departement", new_departement_path %>
</p>            
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% @departements.each do |departement| %>
      <tr>
        <td><%= departement.name %></td>
        <td>
          <%= link_to "Lihat detail", departement, class: "departement-link" %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/departements/new.html.erb
<div class="container">
<h1>New departement</h1>
<div>
  <%= link_to "Back to departements", departements_path %>
</div>

<br>

<%= render "form", departement: @departement %>




</div>

app/views/departements/show.html.erb
<div class="container">


<h2>Detail</h2>
  <p><%= link_to "Back to departements", departements_path, class: "departement-link" %></p>            
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= render @departement %></td>
        <td>
        <%= link_to "Edit this departement", edit_departement_path(@departement), class: "departement-link" %> |
        <div class="destroy-button">
        <%= button_to "Destroy this departement", @departement, method: :delete %>
      </div>
        </td>
      </tr>
  </tbody>
  </table>

  </div>

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>Name:</strong>
    <%= employee.name %>
  </p>

  <p>
    <strong>Departementid:</strong>
    <%= employee.departementID %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :departementID, style: "display: block" %>
    <%= form.number_field :departementID %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="container">

<h1>Editing employee</h1>

<div>
<%= link_to "Back to employees", employees_path %> | <%= link_to "Show this employee", @employee %> 
</div>
<%= render "form", employee: @employee %>

<br>


</div>

app/views/employees/index.html.erb
<div class="container">
<h1>Employees</h1>
  <p><%= link_to "New employee", new_employee_path %></p>            
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>DepartementID</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.departementID %></td>
        <td>
        <%= link_to "Show this employee", employee %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/employees/new.html.erb
<div class="container">
<h1>New employee</h1>
<div>
<%= link_to "Back to employees", employees_path %>
</div>

<br>

<%= render "form", employee: @employee %>




</div>

app/views/employees/show.html.erb
<div class="container">


<h2>Detail</h2>
  <p><%= link_to "Back to employees", employees_path %></p>            
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= render @employee %>
        </td>
        <td>
        <%= link_to "Edit this employee", edit_employee_path(@employee) %>  |
        <div class="destroy-button">
        <%= button_to "Destroy this employee", @employee, method: :delete %>
      </div>
        </td>
      </tr>
  </tbody>
  </table>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "custom", media: "all", "data-turbolinks-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spendings/_form.html.erb
<%= form_with(model: spending) do |form| %>
  <% if spending.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spending.errors.count, "error") %> prohibited this spending from being saved:</h2>

      <ul>
        <% spending.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :employeeID, style: "display: block" %>
    <%= form.number_field :employeeID %>
  </div>

  

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spendings/_spending.html.erb
<div id="<%= dom_id spending %>">
  <p>
    <strong>Employeeid:</strong>
    <%= spending.employeeID %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= spending.date %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= spending.value %>
  </p>

</div>

app/views/spendings/edit.html.erb
<div class="container">

<h1>Editing spending</h1>

<div>
<%= link_to "Back to spendings", spendings_path %> | <%= link_to "Show this spending", @spending %>
</div>
<%= render "form", spending: @spending %>

<br>


</div>

app/views/spendings/index.html.erb
<div class="container">
<h1>Spendings</h1>
  <p><%= link_to "New spending", new_spending_path %></p>            
  <table class="table">
    <thead>
      <tr>
        <th>EmployeeID</th>
        <th>Date</th>
        <th>Value</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% @spendings.each do |spending| %>
      <tr>
        <td><%= spending.employeeID %></td>
        <td><%= spending.date %></td>
        <td><%= spending.value %></td>
        <td>
        <%= link_to "Show this spending", spending %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/spendings/new.html.erb
<div class="container">
<h1>New spending</h1>
<div>
<%= link_to "Back to spendings", spendings_path %>
</div>

<br>

<%= render "form", spending: @spending %>




</div>

app/views/spendings/show.html.erb
<div class="container">


<h2>Detail</h2>
  <p><%= link_to "Back to spendings", spendings_path %></p>            
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <td>
      <%= render @spending %>
      </td>
        <td>
        <%= link_to "Edit this spending", edit_spending_path(@spending) %> |
        <div class="destroy-button">
        <%= button_to "Destroy this spending", @spending, method: :delete %>
      </div>
        </td>
      </tr>
  </tbody>
  </table>

  </div>